---
development:
  cloud_name: oephi
  api_key: '656949628154972'
  api_secret: XwcaJgmpV5VfnLgvaCkKpchzEEs
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: oephi
  api_key: '656949628154972'
  api_secret: XwcaJgmpV5VfnLgvaCkKpchzEEs
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: oephi
  api_key: '656949628154972'
  api_secret: XwcaJgmpV5VfnLgvaCkKpchzEEs
  enhance_image_tag: true
  static_image_support: false
